# Generated by Django 4.0.4 on 2022-07-26 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('identificacion', models.BigIntegerField(blank=True, null=True)),
                ('Nombres', models.CharField(max_length=45)),
                ('Apellidos', models.CharField(max_length=45)),
                ('miembro', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('celular', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('pais', models.CharField(blank=True, max_length=45, null=True)),
                ('institucion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ciudad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('autor_correspondencia', 'autor_correspondencia'), ('Evaluador', 'Evaluador')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo', models.CharField(choices=[('Libre', 'Libre'), ('Ingreso', 'Ingreso'), ('E-poster', 'E-poster')], max_length=45)),
                ('subtipo_trabajo', models.CharField(blank=True, choices=[('Investigacion clinica', 'Investigación clínica'), ('Ciencias basicas', 'Ciencias basicas')], max_length=45, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('resumen_esp', models.TextField()),
                ('palabras_claves', models.TextField()),
                ('resumen_ingles', models.TextField()),
                ('keywords', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True, verbose_name='ultima modificacion')),
                ('Autor_correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.autores')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.cursos')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trabajosC.autores')),
                ('institucion_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.instituciones')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos_has_instituciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajosC.instituciones')),
                ('trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajosC.trabajos')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos_has_autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajosC.autores')),
                ('trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajosC.trabajos')),
            ],
        ),
        migrations.CreateModel(
            name='Tablas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloT', models.CharField(max_length=100)),
                ('tabla', models.FileField(blank=True, default='', null=True, upload_to='tablas/')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.trabajos')),
            ],
        ),
        migrations.CreateModel(
            name='Manuscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloM', models.CharField(max_length=100)),
                ('manuscrito', models.FileField(default='', upload_to='manuscritos/')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.trabajos')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.especialidades'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autores',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajosC.especialidades'),
        ),
        migrations.AddField(
            model_name='autores',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajosC.roles'),
        ),
    ]
