# Generated by Django 4.0.4 on 2022-07-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='manuscritos',
            field=models.FileField(default='', upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='tablas',
            field=models.FileField(blank=True, default='', null=True, upload_to='img/'),
        ),
    ]
