# Generated by Django 4.0.4 on 2022-07-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosC', '0002_alter_trabajos_manuscritos_alter_trabajos_tablas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='identificacion',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='tipo_trabajo',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Investigacion clinica', 'Investigación clínica'), ('Ciencias basicas', 'Ciencias basicas'), ('E-poster', 'E-poster')], max_length=45),
        ),
    ]
