# Generated by Django 4.0.4 on 2022-07-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosC', '0003_alter_autores_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='celular',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
