# Generated by Django 4.0.4 on 2022-07-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosC', '0005_alter_trabajos_fecha_modificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajos',
            name='manuscritos',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='tablas',
        ),
        migrations.CreateModel(
            name='Tablas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloT', models.CharField(max_length=100)),
                ('tabla', models.FileField(blank=True, default='', null=True, upload_to='img/')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.trabajos')),
            ],
        ),
        migrations.CreateModel(
            name='Manuscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloM', models.CharField(max_length=100)),
                ('manuscrito', models.FileField(default='', upload_to='pdfs/')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.trabajos')),
            ],
        ),
    ]
