# Generated by Django 4.0.4 on 2022-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosC', '0008_remove_trabajos_otras_instituciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='subtipo_trabajo',
            field=models.CharField(blank=True, choices=[('Investigacion clinica', 'Investigación clínica'), ('Ciencias basicas', 'Ciencias basicas')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='manuscritos',
            name='manuscrito',
            field=models.FileField(default='', upload_to='manuscritos/'),
        ),
        migrations.AlterField(
            model_name='tablas',
            name='tabla',
            field=models.FileField(blank=True, default='', null=True, upload_to='tablas/'),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='tipo_trabajo',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ingreso', 'Ingreso'), ('E-poster', 'E-poster')], max_length=45),
        ),
    ]
