# Generated by Django 4.0.4 on 2022-07-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosC', '0009_trabajos_subtipo_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='institucion_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajosC.instituciones'),
        ),
        migrations.DeleteModel(
            name='Trabajos_has_instituciones',
        ),
    ]
